name: Build
on:
  push:
    branches: [ main ]

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - run: yarn install
    - run: yarn release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
